name: Swift Lint, Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        run: swiftlint --reporter github-actions-logging
      - name: Swift Build
        run: swift build -v
      - name: Swift Test
        run: swift test -v
