name: Swift Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint (Autofix)
        run: swiftlint autocorrect
      - name: SwiftLint (Report)
        run: swiftlint --reporter github-actions-logging
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
